spring.application.name=docvault


spring.datasource.url=jdbc:mysql://localhost:3306/docvault
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.thymeleaf.cache=false

jwt.secret=my-secret-key-for-docvault-jwt-token-generation-123456
jwt.expiration=86400000
# Server
server.port=9091